-- =============================================================================
-- NoCode Folio — Schema do banco (PRD v3.0: nomenclatura PT-BR + chaves int8)
-- Idempotente: pode ser executado mais de uma vez no SQL Editor do Supabase.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tabela: perfis
-- -----------------------------------------------------------------------------
create table if not exists public.perfis (
  id                bigint generated by default as identity primary key,
  usuario_id        uuid not null unique references auth.users (id) on delete cascade,
  slug              text not null unique,
  nome_completo     text not null default '',
  bio               text not null default '',
  avatar_url        text,
  configuracao_tema jsonb not null default '{}'::jsonb,
  created_at        timestamptz not null default now(),

  -- Validação no banco (o front valida também, mas o banco é a fonte da verdade)
  constraint perfis_slug_formato check (slug ~ '^[a-z0-9][a-z0-9_-]{2,29}$'),
  constraint perfis_slug_reservado check (
    slug not in ('auth', 'onboarding', 'api', 'admin', 'login', 'logout', 'assets', 'static', 'editar')
  ),
  constraint perfis_nome_tamanho check (char_length(nome_completo) <= 80),
  constraint perfis_bio_tamanho check (char_length(bio) <= 280),
  constraint perfis_tema_objeto check (jsonb_typeof(configuracao_tema) = 'object')
);

-- -----------------------------------------------------------------------------
-- Tabela: blocos
-- -----------------------------------------------------------------------------
create table if not exists public.blocos (
  id         bigint generated by default as identity primary key,
  perfil_id  bigint not null references public.perfis (id) on delete cascade,
  tipo       text not null,
  titulo     text,
  conteudo   jsonb not null default '{}'::jsonb,
  colunas    smallint not null default 1,
  linhas     smallint not null default 1,
  ordem      smallint not null default 0,
  visivel    boolean not null default true,
  created_at timestamptz not null default now(),

  constraint blocos_tipo_valido check (tipo in ('link', 'imagem', 'texto', 'mapa', 'video', 'newsletter')),
  constraint blocos_colunas_validas check (colunas between 1 and 4),
  constraint blocos_linhas_validas check (linhas between 1 and 2),
  constraint blocos_titulo_tamanho check (titulo is null or char_length(titulo) <= 80),
  constraint blocos_conteudo_objeto check (jsonb_typeof(conteudo) = 'object'),
  constraint blocos_conteudo_tamanho check (pg_column_size(conteudo) <= 8192)
);

create index if not exists blocos_perfil_ordem_idx on public.blocos (perfil_id, ordem);

-- -----------------------------------------------------------------------------
-- Tabela: leads (captura de e-mails do bloco Newsletter)
-- -----------------------------------------------------------------------------
create table if not exists public.leads (
  id         bigint generated by default as identity primary key,
  perfil_id  bigint not null references public.perfis (id) on delete cascade,
  email      text not null,
  created_at timestamptz not null default now(),

  constraint leads_email_formato check (
    char_length(email) <= 254 and email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'
  ),
  constraint leads_email_unico unique (perfil_id, email)
);

-- -----------------------------------------------------------------------------
-- Onboarding: cria a linha em perfis automaticamente quando o usuário se cadastra
-- -----------------------------------------------------------------------------
create or replace function public.criar_perfil_novo_usuario()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  reservados constant text[] := array['auth', 'onboarding', 'api', 'admin', 'login', 'logout', 'assets', 'static', 'editar'];
  desejado   text := lower(trim(coalesce(new.raw_user_meta_data ->> 'username', '')));
  base_slug  text;
  slug_final text;
begin
  -- Cadastro com senha: usa o nome de usuário escolhido como endereço, se for válido e estiver livre.
  if desejado ~ '^[a-z0-9][a-z0-9_-]{2,29}$'
     and desejado <> all (reservados)
     and not exists (select 1 from public.perfis where slug = desejado) then
    insert into public.perfis (usuario_id, slug, nome_completo, avatar_url)
    values (
      new.id,
      desejado,
      left(coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', ''), 80),
      new.raw_user_meta_data ->> 'avatar_url'
    );
    return new;
  end if;

  -- Sem nome de usuário (Google, link mágico): sugere um endereço a partir do e-mail.
  base_slug := lower(regexp_replace(split_part(coalesce(new.email, ''), '@', 1), '[^a-zA-Z0-9_-]', '', 'g'));
  base_slug := regexp_replace(base_slug, '^[_-]+', '');
  if char_length(base_slug) < 3 then
    base_slug := 'folio' || base_slug;
  end if;
  base_slug := left(base_slug, 24);
  slug_final := base_slug;

  while exists (select 1 from public.perfis where slug = slug_final)
     or slug_final = any (reservados) loop
    slug_final := base_slug || '-' || substr(md5(random()::text), 1, 4);
  end loop;

  insert into public.perfis (usuario_id, slug, nome_completo, avatar_url)
  values (
    new.id,
    slug_final,
    left(coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', ''), 80),
    new.raw_user_meta_data ->> 'avatar_url'
  );
  return new;
end;
$$;

drop trigger if exists ao_criar_usuario on auth.users;
create trigger ao_criar_usuario
  after insert on auth.users
  for each row execute function public.criar_perfil_novo_usuario();

-- -----------------------------------------------------------------------------
-- Reordenação em lote (uma única transação). SECURITY INVOKER: as policies de
-- RLS da tabela blocos continuam valendo — só o dono consegue reordenar.
-- -----------------------------------------------------------------------------
create or replace function public.reordenar_blocos(p_perfil_id bigint, p_ids bigint[])
returns void
language sql
security invoker
set search_path = ''
as $$
  update public.blocos b
     set ordem = (ids.posicao - 1)::smallint
    from unnest(p_ids) with ordinality as ids (id, posicao)
   where b.id = ids.id
     and b.perfil_id = p_perfil_id;
$$;

revoke execute on function public.reordenar_blocos(bigint, bigint[]) from public, anon;
grant execute on function public.reordenar_blocos(bigint, bigint[]) to authenticated;
revoke execute on function public.criar_perfil_novo_usuario() from public, anon, authenticated;

-- -----------------------------------------------------------------------------
-- Privilégios da Data API
-- -----------------------------------------------------------------------------
-- O Supabase concede ALL (inclusive TRUNCATE, que ignora a RLS) a anon/authenticated
-- em tabelas novas. Revoga tudo e concede só o necessário.
-- Privilégios por coluna: id, usuario_id, perfil_id e created_at não podem ser alterados pela API.
revoke all on public.perfis, public.blocos, public.leads from anon, authenticated;
grant select on public.perfis, public.blocos to anon, authenticated;
grant insert (usuario_id, slug, nome_completo, bio, avatar_url, configuracao_tema) on public.perfis to authenticated;
grant update (slug, nome_completo, bio, avatar_url, configuracao_tema) on public.perfis to authenticated;
grant insert (perfil_id, tipo, titulo, conteudo, colunas, linhas, ordem, visivel) on public.blocos to authenticated;
grant delete on public.blocos to authenticated;
grant update (tipo, titulo, conteudo, colunas, linhas, ordem, visivel) on public.blocos to authenticated;
grant insert (perfil_id, email) on public.leads to anon, authenticated;
grant select, delete on public.leads to authenticated;

-- -----------------------------------------------------------------------------
-- RLS: perfis
-- -----------------------------------------------------------------------------
alter table public.perfis enable row level security;

drop policy if exists "perfis_leitura_publica" on public.perfis;
create policy "perfis_leitura_publica" on public.perfis
  for select to anon, authenticated using (true);

drop policy if exists "perfis_criacao_propria" on public.perfis;
create policy "perfis_criacao_propria" on public.perfis
  for insert to authenticated with check ((select auth.uid()) = usuario_id);

drop policy if exists "perfis_edicao_dono" on public.perfis;
create policy "perfis_edicao_dono" on public.perfis
  for update to authenticated
  using ((select auth.uid()) = usuario_id)
  with check ((select auth.uid()) = usuario_id);

-- -----------------------------------------------------------------------------
-- RLS: blocos
-- -----------------------------------------------------------------------------
alter table public.blocos enable row level security;

-- Público vê blocos ativos; o dono vê também os rascunhos (visivel = false).
drop policy if exists "blocos_leitura_publica" on public.blocos;
create policy "blocos_leitura_publica" on public.blocos
  for select to anon, authenticated
  using (
    visivel
    or exists (
      select 1 from public.perfis
      where perfis.id = blocos.perfil_id
        and perfis.usuario_id = (select auth.uid())
    )
  );

drop policy if exists "blocos_criacao_dono" on public.blocos;
create policy "blocos_criacao_dono" on public.blocos
  for insert to authenticated
  with check (
    exists (
      select 1 from public.perfis
      where perfis.id = blocos.perfil_id
        and perfis.usuario_id = (select auth.uid())
    )
  );

drop policy if exists "blocos_edicao_dono" on public.blocos;
create policy "blocos_edicao_dono" on public.blocos
  for update to authenticated
  using (
    exists (
      select 1 from public.perfis
      where perfis.id = blocos.perfil_id
        and perfis.usuario_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1 from public.perfis
      where perfis.id = blocos.perfil_id
        and perfis.usuario_id = (select auth.uid())
    )
  );

drop policy if exists "blocos_exclusao_dono" on public.blocos;
create policy "blocos_exclusao_dono" on public.blocos
  for delete to authenticated
  using (
    exists (
      select 1 from public.perfis
      where perfis.id = blocos.perfil_id
        and perfis.usuario_id = (select auth.uid())
    )
  );

-- -----------------------------------------------------------------------------
-- RLS: leads
-- -----------------------------------------------------------------------------
alter table public.leads enable row level security;

-- Visitantes só podem se inscrever em perfis que têm um bloco Newsletter ativo.
drop policy if exists "leads_inscricao_publica" on public.leads;
create policy "leads_inscricao_publica" on public.leads
  for insert to anon, authenticated
  with check (
    exists (
      select 1 from public.blocos
      where blocos.perfil_id = leads.perfil_id
        and blocos.tipo = 'newsletter'
        and blocos.visivel
    )
  );

-- Apenas o dono do perfil lê/remove seus leads (e-mails são dados pessoais).
drop policy if exists "leads_leitura_dono" on public.leads;
create policy "leads_leitura_dono" on public.leads
  for select to authenticated
  using (
    exists (
      select 1 from public.perfis
      where perfis.id = leads.perfil_id
        and perfis.usuario_id = (select auth.uid())
    )
  );

drop policy if exists "leads_exclusao_dono" on public.leads;
create policy "leads_exclusao_dono" on public.leads
  for delete to authenticated
  using (
    exists (
      select 1 from public.perfis
      where perfis.id = leads.perfil_id
        and perfis.usuario_id = (select auth.uid())
    )
  );

-- -----------------------------------------------------------------------------
-- Storage: bucket público "folio" (avatares e imagens dos blocos)
-- Cada usuário só escreve dentro da pasta com o próprio uid: <uid>/arquivo.ext
-- SVG fica de fora de propósito (pode carregar scripts).
-- -----------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('folio', 'folio', true, 5242880, array['image/png', 'image/jpeg', 'image/webp', 'image/gif'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "folio_upload_dono" on storage.objects;
create policy "folio_upload_dono" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'folio'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "folio_edicao_dono" on storage.objects;
create policy "folio_edicao_dono" on storage.objects
  for update to authenticated
  using (
    bucket_id = 'folio'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "folio_exclusao_dono" on storage.objects;
create policy "folio_exclusao_dono" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'folio'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
